// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package go_graphql_gqlgen

type Employee struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	Contactno string `json:"contactno"`
	Position  string `json:"position"`
}

type NewEmployee struct {
	Name      string `json:"name"`
	Email     string `json:"email"`
	Contactno string `json:"contactno"`
	Position  string `json:"position"`
}
